### ISSUE TITLE
Segfault in nicklist?

### ISSUE THREAD

**Issue by lorenzhs** [torhve/weechat-matrix-protocol-script#4]
```
(gdb) bt
#0  0x00007f89a692f107 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f89a69304e8 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00000000004271b2 in weechat_shutdown (return_code=1, crash=1) at /home/flashcode/build/debian/weechat/src/core/weechat.c:489
#3  <signal handler called>
#4  gui_nicklist_search_nick (buffer=0x2b80fb0, from_group=0x0, name=0x2c5e8d8 "Lorenz") at /home/flashcode/build/debian/weechat/src/gui/gui-nicklist.c:392
#5  0x00007f89a0824843 in weechat_lua_api_nicklist_search_nick (L=0x2872490) at /home/flashcode/build/debian/weechat/src/plugins/lua/weechat-lua-api.c:3647
#6  0x00007f89a05eda28 in luaD_precall (L=L@entry=0x2872490, func=0x2b4af40, nresults=nresults@entry=1) at ldo.c:320
#7  0x00007f89a05f8328 in luaV_execute (L=L@entry=0x2872490, nexeccalls=3, nexeccalls@entry=1) at lvm.c:591
#8  0x00007f89a05ede7d in luaD_call (L=0x2872490, func=0x2b4adc0, nResults=<optimized out>) at ldo.c:378
#9  0x00007f89a05ed0ca in luaD_rawrunprotected (L=L@entry=0x2872490, f=f@entry=0x7f89a05e8730 <f_call>, ud=ud@entry=0x7fff303719c0) at ldo.c:116
#10 0x00007f89a05ee02f in luaD_pcall (L=L@entry=0x2872490, func=func@entry=0x7f89a05e8730 <f_call>, u=u@entry=0x7fff303719c0, old_top=<optimized out>, ef=<optimized out>) at ldo.c:464
#11 0x00007f89a05e9b41 in lua_pcall (L=0x2872490, nargs=nargs@entry=2, nresults=nresults@entry=1, errfunc=errfunc@entry=0) at lapi.c:821
#12 0x00007f89a0816382 in weechat_lua_exec (script=<optimized out>, ret_type=ret_type@entry=0, function=0x2b48240 "cleartyping", format=format@entry=0x7f89a0836a45 "ss", 
    argv=argv@entry=0x7fff30371a70) at /home/flashcode/build/debian/weechat/src/plugins/lua/weechat-lua.c:203
#13 0x00007f89a082f7c9 in weechat_lua_api_hook_timer_cb (data=0x2b2ca20, remaining_calls=<optimized out>) at /home/flashcode/build/debian/weechat/src/plugins/lua/weechat-lua-api.c:2092
#14 0x000000000044fe7f in hook_timer_exec () at /home/flashcode/build/debian/weechat/src/core/wee-hook.c:1173
#15 0x00000000004664a8 in gui_main_loop () at /home/flashcode/build/debian/weechat/src/gui/curses/gui-curses-main.c:390
#16 0x0000000000426bb5 in main (argc=<optimized out>, argv=<optimized out>) at /home/flashcode/build/debian/weechat/src/gui/curses/main.c:41
```

**Comment by lorenzhs** [comment]
full bt:

```gdb
(gdb) bt full
#0  0x00007f89a692f107 in raise () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007f89a69304e8 in abort () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00000000004271b2 in weechat_shutdown (return_code=1, crash=1) at /home/flashcode/build/debian/weechat/src/core/weechat.c:489
No locals.
#3  <signal handler called>
No symbol table info available.
#4  gui_nicklist_search_nick (buffer=0x2b80fb0, from_group=0x0, name=0x2c5e8d8 "Lorenz") at /home/flashcode/build/debian/weechat/src/gui/gui-nicklist.c:392
        ptr_nick = <optimized out>
        ptr_group = <optimized out>
#5  0x00007f89a0824843 in weechat_lua_api_nicklist_search_nick (L=0x2872490) at /home/flashcode/build/debian/weechat/src/plugins/lua/weechat-lua-api.c:3647
        buffer = 0x2b83668 "0x2b80fb0"
        from_group = <optimized out>
        name = 0x2c5e8d8 "Lorenz"
        result = <optimized out>
        lua_function_name = 0x7f89a0836739 "nicklist_search_nick"
#6  0x00007f89a05eda28 in luaD_precall (L=L@entry=0x2872490, func=0x2b4af40, nresults=nresults@entry=1) at ldo.c:320
        ci = <optimized out>
        n = <optimized out>
        cl = <optimized out>
        funcr = <optimized out>
#7  0x00007f89a05f8328 in luaV_execute (L=L@entry=0x2872490, nexeccalls=3, nexeccalls@entry=1) at lvm.c:591
        b = <optimized out>
        nresults = 1
        i = <optimized out>
        ra = <optimized out>
        cl = 0x2b33380
        base = <optimized out>
        k = 0x2b383e0
        pc = 0x2b4c37c
#8  0x00007f89a05ede7d in luaD_call (L=0x2872490, func=0x2b4adc0, nResults=<optimized out>) at ldo.c:378
No locals.
#9  0x00007f89a05ed0ca in luaD_rawrunprotected (L=L@entry=0x2872490, f=f@entry=0x7f89a05e8730 <f_call>, ud=ud@entry=0x7fff303719c0) at ldo.c:116
        lj = {previous = 0x0, b = {{__jmpbuf = {42411152, -7811080997964724915, 1, 42411776, 42411776, 0, 7811237752606967117, 7821124769765934413}, __mask_was_saved = 0, __saved_mask = {__val = {
                  140230682214399, 140229195761828, 46, 140229185487968, 0, 43, 0, 0, 0, 43, 0, 0, 140734002305440, 36722544, 0, 45271584}}}}, status = 0}
#10 0x00007f89a05ee02f in luaD_pcall (L=L@entry=0x2872490, func=func@entry=0x7f89a05e8730 <f_call>, u=u@entry=0x7fff303719c0, old_top=<optimized out>, ef=<optimized out>) at ldo.c:464
        status = <optimized out>
        oldnCcalls = 0
        old_ci = 0
        old_allowhooks = 1 '\001'
        old_errfunc = 0
#11 0x00007f89a05e9b41 in lua_pcall (L=0x2872490, nargs=nargs@entry=2, nresults=nresults@entry=1, errfunc=errfunc@entry=0) at lapi.c:821
        c = {func = 0x2b4adc0, nresults = 1}
        status = <optimized out>
---Type <return> to continue, or q <return> to quit---
        func = <optimized out>
#12 0x00007f89a0816382 in weechat_lua_exec (script=<optimized out>, ret_type=ret_type@entry=0, function=0x2b48240 "cleartyping", format=format@entry=0x7f89a0836a45 "ss", 
    argv=argv@entry=0x7fff30371a70) at /home/flashcode/build/debian/weechat/src/plugins/lua/weechat-lua.c:203
        ret_value = 0x0
        argc = 2
        i = <optimized out>
        ret_i = <optimized out>
        old_lua_current_interpreter = 0x2b94a00
        old_lua_current_script = 0x2b8c690
#13 0x00007f89a082f7c9 in weechat_lua_api_hook_timer_cb (data=0x2b2ca20, remaining_calls=<optimized out>) at /home/flashcode/build/debian/weechat/src/plugins/lua/weechat-lua-api.c:2092
        script_callback = 0x2b2ca20
        func_argv = {0x2b3b0f0, 0x7fff30371a80}
        str_remaining_calls = "-1\000\060\377\177\000\000\000\000\000\000\000\000\000\000\260\032\067\060\377\177\000\000\f\352?0\377\177\000"
        empty_arg = ""
        rc = <optimized out>
        ret = <optimized out>
#14 0x000000000044fe7f in hook_timer_exec () at /home/flashcode/build/debian/weechat/src/core/wee-hook.c:1173
        tv_time = {tv_sec = 1427022960, tv_usec = 678124}
        ptr_hook = 0x2b2ccc0
        next_hook = 0x2d5a6f0
#15 0x00000000004664a8 in gui_main_loop () at /home/flashcode/build/debian/weechat/src/gui/curses/gui-curses-main.c:390
        hook_fd_keyboard = 0x28e4a20
        tv_timeout = {tv_sec = 0, tv_usec = 0}
        read_fds = {fds_bits = {0 <repeats 16 times>}}
        write_fds = {fds_bits = {0 <repeats 16 times>}}
        except_fds = {fds_bits = {0 <repeats 16 times>}}
        max_fd = <optimized out>
        ready = <optimized out>
#16 0x0000000000426bb5 in main (argc=<optimized out>, argv=<optimized out>) at /home/flashcode/build/debian/weechat/src/gui/curses/main.c:41
No locals.
```

**Comment by lorenzhs** [comment]
```
(gdb) f 4
#4  gui_nicklist_search_nick (buffer=0x1f012c0, from_group=0x0, name=0x1f14ec8 "Lorenz") at /home/flashcode/build/debian/weechat/src/gui/gui-nicklist.c:392
392     /home/flashcode/build/debian/weechat/src/gui/gui-nicklist.c: No such file or directory.
(gdb) p *buffer
$1 = {plugin = 0x3178303a70756f72, plugin_name_for_upgrade = 0x6c2c303562366464 <Address 0x6c2c303562366464 out of bounds>, number = 1601467233, layout_number = 1801677166,
  layout_number_merge_order = 829960250, name = 0x5f7478656e2c3062 <Address 0x5f7478656e2c3062 out of bounds>, full_name = 0x78303a70756f7267 <Address 0x78303a70756f7267 out of bounds>,
  short_name = 0x2c30666236646431 <Address 0x2c30666236646431 out of bounds>, type = 1701667182, notify = 829960250, num_displayed = 1714775140, active = 1881944121, hidden = 1852142177,
  zoomed = 2016426612, print_hooks_enabled = 842294577, day_change = 3158369, clear = 809001570, filter = 1768843564, close_callback = 0x64657a696c616974, close_callback_data = 0x121,
  closing = 1717924464, title = 0x74676e656c5f7861 <Address 0x74676e656c5f7861 out of bounds>, own_lines = 0x3334653178303a68, mixed_lines = 0x666675622c303966, lines = 0x6c5f78616d5f7265,
  time_for_each_line = 1952935525, chat_refresh_needed = 1701994344, nicklist = 1936028262, nicklist_case_sensitive = 2016426600, nicklist_root = 0x2c30336633346531,
  nicklist_max_length = 1701734764, nicklist_display_groups = 1768447859, nicklist_count = 1852138596, nicklist_groups_count = 829960250, nicklist_nicks_count = 1697854565,
  nicklist_visible_count = 1881944115, nickcmp_callback = 0x616d5f7869666572, nickcmp_callback_data = 0x6874676e656c5f78, input = 1717924447, input_callback = 0x303434653178303a,
  input_callback_data = 0x65666675622c3031, input_get_unknown_commands = 1634557810, input_buffer = 0x3178303a6874676e <Address 0x3178303a6874676e out of bounds>, input_buffer_alloc = 1697854565,
  input_buffer_size = 1814835298, input_buffer_length = 1936027241, input_buffer_pos = 1970234207, input_buffer_1st_display = 809137262, input_undo_snap = 0x7269662c30336433,
  input_undo = 0x3a656e696c5f7473, last_input_undo = 0x3562333465317830, ptr_input_undo = 0x6c5f7473616c2c30, input_undo_count = 979725929, completion = 0x616c2c3066623334,
  history = 0x5f646165725f7473, last_history = 0x3178303a656e696c, ptr_history = 0x662c303963333465, num_history = 1953722985, text_search = 1852402783, text_search_exact = 1869504357,
  text_search_regex = 1701994356, text_search_regex_compiled = 0x34653178303a6461, text_search_where = 811754547, text_search_found = 0, text_search_input = 0x7f4b54cfbe98 "",
  highlight_words = 0xa1 <Address 0xa1 out of bounds>, highlight_regex = 0x3a656c6269736976 <Address 0x3a656c6269736976 out of bounds>, highlight_regex_compiled = 0x3361343465317830,
  highlight_tags_restrict = 0x7869666572702c30 <Address 0x7869666572702c30 out of bounds>, highlight_tags_restrict_count = 1819239263, highlight_tags_restrict_array = 0x3062393434653178,
  highlight_tags = 0x3a7869666572702c <Address 0x3a7869666572702c out of bounds>, highlight_tags_count = 1697740848, highlight_tags_array = 0x3a726f6c6f632c30,
  hotlist_max_level_nicks = 0x6238343465317830, keys = 0x3a70756f72672c30, last_key = 0x3937343465317830, keys_count = 1701719088, local_variables = 0x653178303a6b6369,
  prev_buffer = 0x72702c3035623434, next_buffer = 0x3a6b63696e5f7665}
```

**Comment by lorenzhs** [comment]
```
(gdb) bt full
#0  0x00007f7d24428165 in *__GI_raise (sig=<optimized out>) at ../nptl/sysdeps/unix/sysv/linux/raise.c:64
        pid = <optimized out>
        selftid = <optimized out>
#1  0x00007f7d2442b3e0 in *__GI_abort () at abort.c:92
        act = {__sigaction_handler = {sa_handler = 0x7f7d1e6e15e8 <weechat_lua_plugin>, sa_sigaction = 0x7f7d1e6e15e8 <weechat_lua_plugin>}, sa_mask = {__val = {140175456274828, 14560048, 
              140175459470912, 0, 0, 140175455800224, 140175481196544, 140175358170600, 4294967295, 14420000, 1, 7164056, 0, 26515432, 140175358170600, 0}}, sa_flags = 631425522, sa_restorer = 0x1}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00000000004271b2 in weechat_shutdown (return_code=1, crash=1) at /home/flashcode/build/debian/weechat/src/core/weechat.c:489
No locals.
#3  <signal handler called>
No symbol table info available.
#4  gui_nicklist_search_nick (buffer=0x1b6c960, from_group=0x0, name=0x19497e8 "Lorenz") at /home/flashcode/build/debian/weechat/src/gui/gui-nicklist.c:392
        ptr_nick = <optimized out>
        ptr_group = <optimized out>
#5  0x00007f7d1e4c7843 in weechat_lua_api_nicklist_search_nick (L=0x1930010) at /home/flashcode/build/debian/weechat/src/plugins/lua/weechat-lua-api.c:3647
        buffer = 0x1b52378 "0x1b6c960"
        from_group = <optimized out>
        name = 0x19497e8 "Lorenz"
        result = <optimized out>
        lua_function_name = 0x7f7d1e4d9739 "nicklist_search_nick"
#6  0x00007f7d1e290a28 in luaD_precall (L=L@entry=0x1930010, func=0x1968110, nresults=nresults@entry=1) at ldo.c:320
        ci = <optimized out>
        n = <optimized out>
        cl = <optimized out>
        funcr = <optimized out>
#7  0x00007f7d1e29b328 in luaV_execute (L=L@entry=0x1930010, nexeccalls=3, nexeccalls@entry=1) at lvm.c:591
        b = <optimized out>
        nresults = 1
        i = <optimized out>
        ra = <optimized out>
        cl = 0x19752c0
        base = <optimized out>
        k = 0x19554b0
        pc = 0x196956c
#8  0x00007f7d1e290e7d in luaD_call (L=0x1930010, func=0x1967f90, nResults=<optimized out>) at ldo.c:378
No locals.
#9  0x00007f7d1e2900ca in luaD_rawrunprotected (L=L@entry=0x1930010, f=f@entry=0x7f7d1e28b730 <f_call>, ud=ud@entry=0x7fff7e1af970) at ldo.c:116
        lj = {previous = 0x0, b = {{__jmpbuf = {26411024, -72918229627336603, 1, 26411648, 26411648, 0, 72635337356707941, 1914334167140453}, __mask_was_saved = 0, __saved_mask = {__val = {
                  4294967295, 33188, 0, 140175459459008, 0, 2, 140175459484544, 22901800883, 2115696998, 0, 140735309085008, 140735309085030, 14144624, 140735309085119, 14378880, 
                  140735309085183}}}}, status = 0}
#10 0x00007f7d1e29102f in luaD_pcall (L=L@entry=0x1930010, func=func@entry=0x7f7d1e28b730 <f_call>, u=u@entry=0x7fff7e1af970, old_top=<optimized out>, ef=<optimized out>) at ldo.c:464
        status = <optimized out>
        oldnCcalls = 0
        old_ci = 0
        old_allowhooks = 1 '\001'
        old_errfunc = 0
#11 0x00007f7d1e28cb41 in lua_pcall (L=0x1930010, nargs=nargs@entry=2, nresults=nresults@entry=1, errfunc=errfunc@entry=0) at lapi.c:821
---Type <return> to continue, or q <return> to quit---
        c = {func = 0x1967f90, nresults = 1}
        status = <optimized out>
        func = <optimized out>
#12 0x00007f7d1e4b9382 in weechat_lua_exec (script=<optimized out>, ret_type=ret_type@entry=0, function=0x1953160 "cleartyping", format=format@entry=0x7f7d1e4d9a45 "ss", 
    argv=argv@entry=0x7fff7e1afa20) at /home/flashcode/build/debian/weechat/src/plugins/lua/weechat-lua.c:203
        ret_value = 0x0
        argc = 2
        i = <optimized out>
        ret_i = <optimized out>
        old_lua_current_interpreter = 0x19b78e0
        old_lua_current_script = 0x19a1dd0
#13 0x00007f7d1e4d27c9 in weechat_lua_api_hook_timer_cb (data=0x194a420, remaining_calls=<optimized out>) at /home/flashcode/build/debian/weechat/src/plugins/lua/weechat-lua-api.c:2092
        script_callback = 0x194a420
        func_argv = {0x1956bd0, 0x7fff7e1afa30}
        str_remaining_calls = "-1\000~\377\177\000\000\f\352\037~\377\177\000\000\320\373\032~\377\177\000\000\377\377\377\377\000\000\000"
        empty_arg = ""
        rc = <optimized out>
        ret = <optimized out>
#14 0x000000000044feaf in hook_timer_exec () at /home/flashcode/build/debian/weechat/src/core/wee-hook.c:1173
        tv_time = {tv_sec = 1427042137, tv_usec = 290548}
        ptr_hook = 0x194a180
        next_hook = 0x1b72860
#15 0x00000000004664d8 in gui_main_loop () at /home/flashcode/build/debian/weechat/src/gui/curses/gui-curses-main.c:390
        hook_fd_keyboard = 0x1709ef0
        tv_timeout = {tv_sec = 0, tv_usec = 0}
        read_fds = {fds_bits = {0 <repeats 16 times>}}
        write_fds = {fds_bits = {0 <repeats 16 times>}}
        except_fds = {fds_bits = {0 <repeats 16 times>}}
        max_fd = <optimized out>
        ready = <optimized out>
#16 0x0000000000426bb5 in main (argc=<optimized out>, argv=<optimized out>) at /home/flashcode/build/debian/weechat/src/gui/curses/main.c:41
No locals.
```

**Comment by torhve** [comment]
Thanks for helping me resolve this issue. I have pushed a fix.
